language: perl # prevent it from using perlbrew which does not support threads
perl:
  - "5.18-extras"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl
install:
  - perlbrew list
  - sudo apt-get install libdbus-1-dev
  - cpanm -nq JSON Data::Dump
  - git clone git://github.com/os-autoinst/os-autoinst
  - cpanm -nq `cat os-autoinst/DEPENDENCIES.txt`
script:
  - make test
sudo: required
