language: perl # prevent it from using perlbrew which does not support threads
perl:
  - "5.18-extras"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl
install:
  - perlbrew list
  - sudo apt-get install libdbus-1-dev
  # waiting for https://rt.cpan.org/Public/Bug/Display.html?id=106808
  - cpanm -nq ExtUtils::MakeMaker@7.04 Net::DBus
  - cpanm -nq JSON Data::Dump
  - git clone git://github.com/os-autoinst/os-autoinst
  - ln -s os-autoinst/tools .
  - cpanm -nq `cat os-autoinst/DEPENDENCIES.txt`
script:
  - make test
sudo: required
