language: perl # prevent it from using perlbrew which does not support threads
perl:
  - "5.18-extras"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --perl
install:
  - perlbrew list
  - sudo apt-get install libdbus-1-dev libssh2-1-dev
  - git clone git://github.com/os-autoinst/os-autoinst
  - ln -s os-autoinst/tools .
  - ln -s os-autoinst/cpanfile .
  - cpanm -nq --installdeps .
script:
  - make test
sudo: required
