---
name: Run a basic openQA test
# yamllint disable-line rule:truthy
on:
  pull_request_target:
  # Note how this runs on:pull_request_target and not on:pull_request!
  # The difference is that this runs always with the context of the master
  # branch. This is necessary to allow accessing the API credential secrets.
  workflow_dispatch:
env:
  OPENQA_HOST: ${{ vars.OPENQA_URL }}
  OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
  OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
  GH_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  GH_REF: ${{ github.event.pull_request.head.ref }}
  GH_PR_BODY: ${{ github.event.pull_request.body }}

jobs:
  trigger_and_monitor_openqa:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - uses: actions/checkout@v3
      - name: Determine the latest Tumbleweed build on o3
        id: latest_build
        run: >-
          echo build=$(openqa-cli api
          --host ${OPENQA_HOST:-https://openqa.opensuse.org}
          job_groups/${OPENQA_BUILD_LOOKUP_GROUP_ID:-1}/build_results limit_builds=1 only_tagged=1
          | jq -r '[ .build_results[] | select(.tag.description=="published") | .build ][]'
          ) >> "$GITHUB_OUTPUT"
      - name: Trigger and monitor a basic openQA test on o3
        run: >-
          openqa-cli schedule
          --monitor
          --host "${OPENQA_HOST:-https://openqa.opensuse.org}/"
          --apikey "$OPENQA_API_KEY" --apisecret "$OPENQA_API_SECRET"
          --param-file SCENARIO_DEFINITIONS_YAML=scenario-definitions.yaml
          DISTRI=openSUSE VERSION=Tumbleweed FLAVOR=github ARCH=x86_64
          HDD_1=opensuse-Tumbleweed-x86_64-${{ steps.latest_build.outputs.build }}-textmode@64bit.qcow2
          UEFI_PFLASH_VARS=opensuse-Tumbleweed-x86_64-${{ steps.latest_build.outputs.build }}-textmode@64bit-uefi-vars.qcow2
          BUILD="$GH_REPO.git#$GH_REF" _GROUP_ID="${OPENQA_SCHEDULE_GROUP_ID:-118}"
          CASEDIR="$GITHUB_SERVER_URL/$GH_REPO.git#$GH_REF"
  clone_mentioned_job:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - name: Clone and monitor job mentioned in PR description
        uses: os-autoinst/scripts/actions/clone-job@master
